### ISSUE TITLE
Accommodate CDNs

### ISSUE THREAD

**Issue by delapuente** [mozilla/wp-offline-content#29]
We should do our best to accommodate for CDNs

At this moment we're assuming the user wants to cache files on their domain.  Could it be as easy as adding an input box and asking for a hostname?  That way they can use the CDN hostname instead?

The only issue I can think of with this setup is the case where a file is updated locally, isn't immediately sent to CDN, but the user downloads the SW with updated hash and doesn't get the CDN file once it _is_ pushed to CDN...

**Comment by darkwing** [comment]
The edge case @delapuente stated is a real thorn.  One thought I had was (not sure upon which event), we could get the CDN version and local version and compare their contents to ensure they're in sync.
