### ISSUE TITLE
 Cache some WordPress core items

### ISSUE THREAD

**Issue by delapuente** [mozilla/wp-offline-content#33]
jQuery and other vital WordPress resources are not in the theme folder. We should detect these and recommend them for caching.

**Comment by darkwing** [comment]
You can get the list of enqueue'd URLs here:

https://gist.github.com/darkwing/8ef9e8450be20fd349b8

My latest idea was to display a series of checkboxes in admin so the user could identify which they'd like to cache, then in the SW use `cache.addAll()` on the array of selected files *but don't return the promise*; i.e. cache them "in the background" and don't let the SW fail if an enqueue'd URL fails.

Logic behind the "background" cache is that any plugin or theme can add enqueue'd URLs and IMO they're less reliable than file system theme file URLs.
