### ISSUE TITLE
WP_SW_Manager is not loading.

### ISSUE THREAD

**Issue by usamanoman** [mozilla/wp-offline-content#36]
When I tried to activate the plugin I got that Mozilla\WP_SW_Manager class not found.

I have fixed the errors by replacing "Autoload" with each file in the vendor folder.

But as soon as I installed "Add to home screen" it gave me error of Duplicate class declaration. I removed all the files again and I am good to go.

So solution if anyone stuck at this point would be:
1- If used with "Add to home Screen" -> Just remove the autoload file from wp-offline-content.php.
2- If used without "Add to home Screen" -> Remove the autoload file from wp-offline-content.php and include following files.
include_once(plugin_dir_path(**FILE**) . 'vendor/marco-c/wp_serve_file/WP_Serve_File.php');
include_once(plugin_dir_path(**FILE**) . 'vendor/mozilla/wp-sw-manager/WP_SW_Manager_Router.php');
include_once(plugin_dir_path(**FILE**) . 'vendor/mozilla/wp-sw-manager/WP_SW_Manager_Combinator.php');
include_once(plugin_dir_path(**FILE**) . 'vendor/mozilla/wp-sw-manager/WP_SW_Manager.php');

I hope the issue will be solved in future anyway. Keep up the good work.

Thanks.

**Comment by delapuente** [comment]
Did you update all the plugins?

**Comment by delapuente** [comment]
I just tested the complete suite:
  * Offline Content 0.6.0
  * Offline Shell 0.4.0
  * Web Push 1.1.7
  * Add To Home Screen 0.3.0

And they are working well.

**Comment by usamanoman** [comment]
How do I get rid of this? :(

http://prntscr.com/asoc6t

This is on fresh installation. Let me know what's the fix.

**Comment by usamanoman** [comment]
Offline content on my site "Eventistan.com" doesnt seem to work.

Can you please try with mobile? Here is the screenshot of the debug page.

![screenshot_2016-04-16-11-08-18](https://cloud.githubusercontent.com/assets/8258785/14579467/cb932004-03c3-11e6-9355-93ffc21a2ca3.png)

**Comment by delapuente** [comment]
You need the latest versions of all the plugins. Can you tell me if you have other plugins from above and which versions?

**Comment by usamanoman** [comment]
I installed latest version 0.6.1 of Offline content and it still has the same issue:
http://prntscr.com/au18v9

**Comment by delapuente** [comment]
Which **other** plugins do you have? Can I see the versions of the **other** plugins, please?

**Comment by LightBen** [comment]
Hi, anything new on that?
I installed the 4 plugins, last versions, and for Add to Home screen, push and offline content I get installion couldn't be installed because of fatal error: Mozilla\WP_SW_Manager not found
My other extensions are Polylang, maintenance, contact form 7, advanced custom fields.
Thanks =)

**Comment by delapuente** [comment]
Sorry, I'm not ignoring you, but I don't have bandwidth enough, so PR are welcome.
