### ISSUE TITLE
Offline Content on Eventistan

### ISSUE THREAD

**Issue by usamanoman** [mozilla/wp-offline-content#44]
Offline content on my site "Eventistan.com" doesnt seem to work.

Can you please try with mobile? Here is the screenshot of the debug page.

![screenshot_2016-04-16-11-08-18](https://cloud.githubusercontent.com/assets/8258785/14579467/cb932004-03c3-11e6-9355-93ffc21a2ca3.png)

**Comment by delapuente** [comment]
For some reason, pages are tried to be fetch on http and not https. Let me dig into that.

**Comment by usamanoman** [comment]
Hi the issue was with my website configuration (My website was surfing https automatically but I still have http in my settings). But the issue is consistent I can't surf the site offline on my Android.

Here is the screenshot of the debugger now; It seems to work fine now but app is not working offline at all.
![screenshots_2016-04-19-10-20-52](https://cloud.githubusercontent.com/assets/8258785/14628635/37d5e9fc-0619-11e6-890c-b0ea2d75614e.png)

**Comment by delapuente** [comment]
Current version only caches published pages or visited posts at the moment. I checked your site now but it seems the plugin is not enabled. We are planning to release a [v1.0.0 by mids of next month](https://github.com/mozilla/wp-offline-content/milestones) with a [reachable content discovery feature](https://github.com/mozilla/wp-offline-content/issues/8) to allow your readers to navigate to non visited posts in addition of combining the functionality of the [Offline Shell plugin](https://github.com/mozilla/wp-offline-content/tree/fusion).

Anyway, track #8 to see updates about this specific feature.
